name: changeNameOfGitHubAction

on:
  push:
    branches: [ master, develop ]

# 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
    # Rrn a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy my project

    - name: hello world 출력!!
      run: echo Hello, world!
    - name: 디렉토리 출력!!
      run: ls -al
    - name: 파이썬 버전 출력!!
      run: python -V
