name: changeNameOfGitHubAction


on:
  push:
    branches: [ master, develop ]

#     paths:
#      - "test_code/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      
    # Rrn a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy my project

    - name: hello world 출력!!
      run: echo Hello, world!
    - name: 디렉토리 출력!!
      run: ls -al
    - name: 파이썬 버전 출력!!
      run: python -V
    - name: Run a one-line script
      run: echo Hello, world!
  
    - uses: actions/checkout@v2
    - name: 3. pip 업그레이드
      run: python -m pip install --upgrade pip
    
    - name: 4. 환경설정
      run: pip install -r requirements.txt
    
    - name: Run python
      run: python test_code/test.py
      
    - name: Commit files
      run: |
        git config --local user.email "olaf@buzzni.com"
        git config --local user.name "olaf"
        git add .
        git commit -m "Olaf test code"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
