name: Test API
on:
  workflow_call:
    inputs:
      api_name:
        required: true
        type: string

    outputs:
      result:
        description: Test status
        value: ${{ jobs.integration_test.conclusion }}

env:
  python-version: 3.9.12

jobs:
  integration_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_DB: order
          POSTGRES_USER: buzzni
          POSTGRES_PASSWORD: postgres-local
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6.2-alpine
        ports:
          - 6380:6379

    steps:
      - name: Test environment Setup Python..
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Pull github repositories...
        uses: actions/checkout@v2

      - name: Install dependencies..
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: API Test
        run: |
          pytest -c pytest.ini
