name: Test API
on:
  workflow_call:
    inputs:
      api_name:
        required: true
        type: string

    outputs:
      result:
        description: Test status
        value: ${{ jobs.integration_test.conclusion }}

env:
  env: test
  DB_HOST: localhost
  DB_USERNAME: buzzni
  DB_PASSWORD: buzznilocal


jobs:
  integration_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9.12]
        os: [ubuntu-latest]

    steps:
      - name: Test environment Setup Python..
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pull github repositories...
        uses: actions/checkout@v2

      - name: Install dependencies..
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: API Test
        run: |
          pytest
